// Code generated by mockery v2.53.3. DO NOT EDIT.

package mockfood

import (
	context "context"

	food "github.com/gatsu420/marianne/app/usecases/food"
	mock "github.com/stretchr/testify/mock"
)

// MockUsecase is an autogenerated mock type for the Usecase type
type MockUsecase struct {
	mock.Mock
}

type MockUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUsecase) EXPECT() *MockUsecase_Expecter {
	return &MockUsecase_Expecter{mock: &_m.Mock}
}

// GetFood provides a mock function with given fields: ctx, id
func (_m *MockUsecase) GetFood(ctx context.Context, id int) (*food.GetFoodRow, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetFood")
	}

	var r0 *food.GetFoodRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*food.GetFoodRow, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *food.GetFoodRow); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*food.GetFoodRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUsecase_GetFood_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFood'
type MockUsecase_GetFood_Call struct {
	*mock.Call
}

// GetFood is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockUsecase_Expecter) GetFood(ctx interface{}, id interface{}) *MockUsecase_GetFood_Call {
	return &MockUsecase_GetFood_Call{Call: _e.mock.On("GetFood", ctx, id)}
}

func (_c *MockUsecase_GetFood_Call) Run(run func(ctx context.Context, id int)) *MockUsecase_GetFood_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockUsecase_GetFood_Call) Return(_a0 *food.GetFoodRow, _a1 error) *MockUsecase_GetFood_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsecase_GetFood_Call) RunAndReturn(run func(context.Context, int) (*food.GetFoodRow, error)) *MockUsecase_GetFood_Call {
	_c.Call.Return(run)
	return _c
}

// ListFood provides a mock function with given fields: ctx, args
func (_m *MockUsecase) ListFood(ctx context.Context, args *food.ListFoodArgs) ([]food.ListFoodRow, error) {
	ret := _m.Called(ctx, args)

	if len(ret) == 0 {
		panic("no return value specified for ListFood")
	}

	var r0 []food.ListFoodRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *food.ListFoodArgs) ([]food.ListFoodRow, error)); ok {
		return rf(ctx, args)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *food.ListFoodArgs) []food.ListFoodRow); ok {
		r0 = rf(ctx, args)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]food.ListFoodRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *food.ListFoodArgs) error); ok {
		r1 = rf(ctx, args)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUsecase_ListFood_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListFood'
type MockUsecase_ListFood_Call struct {
	*mock.Call
}

// ListFood is a helper method to define mock.On call
//   - ctx context.Context
//   - args *food.ListFoodArgs
func (_e *MockUsecase_Expecter) ListFood(ctx interface{}, args interface{}) *MockUsecase_ListFood_Call {
	return &MockUsecase_ListFood_Call{Call: _e.mock.On("ListFood", ctx, args)}
}

func (_c *MockUsecase_ListFood_Call) Run(run func(ctx context.Context, args *food.ListFoodArgs)) *MockUsecase_ListFood_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*food.ListFoodArgs))
	})
	return _c
}

func (_c *MockUsecase_ListFood_Call) Return(_a0 []food.ListFoodRow, _a1 error) *MockUsecase_ListFood_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsecase_ListFood_Call) RunAndReturn(run func(context.Context, *food.ListFoodArgs) ([]food.ListFoodRow, error)) *MockUsecase_ListFood_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUsecase creates a new instance of MockUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUsecase {
	mock := &MockUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
